### ISSUE TITLE
[medicine] SearchPage, MedicinePage, MedicineItem 기능 구현 및 퍼블리싱

### ISSUE THREAD

**Issue by zziglet** [Cloudong/ku-pillwith-client#6]
### 🥑ISSUE
SearchPage, MedicinePage, MedicineItem 기능 구현 및 퍼블리싱

### 🥑TODO

- [x] 검색페이지 퍼블리싱
- [x] 검색페이지 api 연결
- [x] 약 목록 아이템 퍼블리싱
- [x] 약 클릭 이벤트 구현(약 상세페이지로 이동)
- [x] 약 상세페이지 퍼블리싱
- [x] 약 상세페이지 api 연결 (약 id로 상세 정보 불러오기)
